spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asset_registry
    username: asset
    password: asset
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/dev
server:
  port: 8080

springdoc:
  swagger-ui.enabled: true
  api-docs.enabled: true
